# Generated by Django 4.1 on 2023-03-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='flights',
            new_name='p_flights',
        ),
    ]
